spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/encomendas
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true